### ISSUE TITLE
are these container comments functional in any way?

### ISSUE THREAD

**Issue by fredzannarbor** [TangleSpace/hydralit-example#2]
#------------all valid container references, do not initilise or page config will not be applied (this is from beta containers, beta, who knew!).
    #my_container = st.sidebar
    # my_container = st.sidebar.beta_container
    # my_container = st.sidebar.beta_columns
    #my_container = st
    # my_container = st.beta_container
    # my_container = st.beta_columns
    
1) Are these functional in any way when commented?
2) What do they do when uncommented? Is this how I would make a sidebar?

**Comment by TangleSpace** [comment]
you can specify where the menu is placed. in the new release these will be deprecated as the nav is a dedicated component, the Streamlit container will remain as well as the ability to use standard Streamlit controls for the nav, but these comments are just to show examples of what containers the nav could be put into, including the sidebar. best to look at the refreshed code recently uploaded.
