### ISSUE TITLE
content appears twice on pages triggered from buttons on Home page

### ISSUE THREAD

**Issue by fredzannarbor** [TangleSpace/hydralit-example#5]
When you launch a page from the text button links on the Home page, its content appears twice, e.g.

function result (SolarMach page)
function result (SolarMach page)

This only occurs from the text button links in the center of the page, *not* from the links in the complex nav.

I tested this on a fresh clone of the hydralit-example and with all the hydralits at their latest version.

**Comment by TangleSpace** [comment]
Thanks have logged this in the Hydralit package issues log, https://github.com/TangleSpace/hydralit/issues/5
