### ISSUE TITLE
Sticky navbar hides streamlit menu

### ISSUE THREAD

**Issue by pwm1234-sri** [TangleSpace/hydralit-example#6]
When I use a sticky navbar, that covers up the streamlit menu. You can see this in the example app when selecting "Use Hyradlit Navbar" and by not selecting "Use Sticky Navbar" and "Hide Streamlit Markers". This shows the streamlit menu in the top right of the page. 

![image](https://user-images.githubusercontent.com/73309596/140587828-c4a6cf55-cc97-4b1f-b6a3-2e175c8f1c35.png)

Then by selecting "Use Sticky Navbar" this covers up the streamlit menu.
![image](https://user-images.githubusercontent.com/73309596/140587918-90f0004c-2664-4d5f-a824-08d98f580dcb.png)

**Comment by TangleSpace** [comment]
and? if you want the nav pinned to the top of the page, the st hamburger menu is in the way, if you want the hamburger, then don't use the sticky setting, the navbar wasn't built to magically incorporate the st crap menu as well. the next version of the navbar will change the sticky behaviour and just pin it to the top s the hamburger menu is accessible in addition to the navbar, however, it till be pinned, not sticky.

**Comment by pwm1234-sri** [comment]
Okay. Thanks for the explanation.

**Comment by TangleSpace** [comment]
you can mix and match how you want the menu to look, please see the readme https://github.com/TangleSpace/hydralit_components
